version: '3.3'

services:
  postgres:
    image: postgres:12.1-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: books
      POSTGRES_USER: books
      POSTGRES_PASSWORD: books
    networks:
      - books-api

networks:
  books-api:
    driver: bridge
